config/routes.rb
Rails.application.routes.draw do
  # get 'games/create'
  # get 'games/edit'
  # get 'games/update'
  # get 'games/show'
  resources :games
  # get 'pages/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "page/blog"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	
	QUESTIONS = [ 
		"A t'il les yeux clairs ?",
		"Est ce un homme ?",
		"Est t-il vegan ?",
		"Est il originaire d'aquitaine ?"
	]

  def create
  	# créer le tableau de réponses vide
  	@game = Game.create
  	redirect_to edit_game_path(@game["id"], question_id: 0), method: :get
  end

  def edit
  	#@id = params ["id"]
  	@question = QUESTIONS[params["question_id"].to_i]
  end

  def update
  	redirect_to game_path(1), method: :get
  end

  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # [...]
  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/edit.html.erb
<div class="banner" style="background-image: url('https://cdn.pixabay.com/photo/2013/06/10/08/54/morocco-123964_960_720.jpg');">

<h1>Joue avec nous !</h1>
<!-- <p>Find me in app/views/games/edit.html.erb</p> -->

<h3> As-tu déjà regardé Aladin ?</h3>

<% @question %>
<%= link_to("Oui !", game_path(params["id"], answer:"yes"), method: :put, class: "btn btn-success yes")%>
<%= link_to("Non !", game_path(params["id"], answer:"non"), method: :put, class: "btn btn-danger no")%>

<div class="link">
		
	</div>
	<img src="http://www.imagespourtoi.com/lesimages/aladdin/image-aladdin-1.png" alt="Aladin" class="genie"/>
	


</div>

app/views/games/show.html.erb
<h1>TADAAAAAAH</h1>
<p>Voici notre petit Akinator chéri !</p>

app/views/games/update.html.erb
<h1>Games#update</h1>
<p>Find me in app/views/games/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Akinator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/blog.html.erb
<h1>Mon blog</h1>
<h2>Mon 1er article</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur sequi reiciendis,
ipsam esse temporibus, nobis doloremque vitae, hic mollitia voluptatibus quas aperiam
quam tenetur harum perspiciatis non, illum enim impedit.</p>

app/views/pages/home.html.erb
<h1>Home</h1>

<body>

<p>Bienvenue sur Akinator !</p>

<%= link_to( "Commencer le jeu !", games_path, method: :post, class: "btn btn-warning") %>

<div class="container">
			
	<div class="link">
		
	</div>
	<img src="https://vignette.wikia.nocookie.net/kingdomhearts/images/2/2f/Genie_KHREC.png/revision/latest?cb=20111024141553&path-prefix=fr" alt="Génie" class="genie"/>
	<div class= "time"> <%= Time.now.strftime("%d/%m/%y ") %></div>

</div>

</body>